apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm-deployment
  namespace: nginx-helmchart
spec:
  replicas: {{ .Values.nginx1.replicaCount }}
  selector:
     matchLabels:
       app: nginx
       helm: nginx
  template:
    metadata:
      labels:
        app: nginx
        helm: nginx
    spec:
      containers:
       - image: "nginx:{{ .Values.nginx1.image.tag }}"
         name: nginx-helm
         ports:
         - containerPort: 80
