apiVersion: v1
kind: Service
metadata:
   name: nginx3-nodeport
   namespace: mynginx
spec:
   type: NodePort
   selector:
     helm: nginx3
   ports:
   - port: 80
     targetPort: 80
     nodePort: {{ .Values.nginx3.service.nodeport}}
     protocol: TCP
