apiVersion: v1
kind: Service
metadata:
  name: nginx-helm-svc
  namespace: mynginx
spec:
   type: NodePort
   selector:
     helm: nginx
   ports:
   - port: 80
     targetPort: 80
     nodePort: {{ .Values.nginx1.service.nodeport }}
     protocol: TCP
