apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm-deployment2
  namespace: mynginx
spec:
  replicas: {{ .Values.nginx2.replicaCount }}
  selector:
     matchLabels:
       app: nginx
       helm: nginx2
  template:
    metadata:
      labels:
        app: nginx
        helm: nginx2
    spec:
      containers:
       - image: "nginx:{{ .Values.nginx2.image.tag }}"
         name: nginx-helm
         ports:
         - containerPort: 80
