apiVersion: v1
kind: Service
metadata:
   name: nginx2-nodeport
spec:
   type: NodePort
   selector:
     helm: nginx2
   ports:
   - port: 80
     targetPort: 80
     nodePort: {{ .Values.nginx2.service.nodeport}}
     protocol: TCP
