apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm-deployment3
  namespace: nginx-helmchart
spec:
  replicas: {{ .Values.nginx3.replicaCount }}
  selector:
     matchLabels:
       app: nginx
       helm: nginx3
  template:
    metadata:
      labels:
        app: nginx
        helm: nginx3
    spec:
      containers:
       - image: "nginx:{{ .Values.nginx3.image.tag }}"
         name: nginx-helm
         ports:
         - containerPort: 80
         volumeMounts:
           - name: volume-config
             mountPath: /usr/share/nginx/html
      volumes:
       - name: volume-config
         persistentVolumeClaim:
             claimName: nginx-pvc

