apiVersion: v1
kind: PersistentVolume
metadata:
   name: nginx-pv
   namespace: mynginx
spec:
  hostPath:
    path: /etc/nginx/content
  storageClassName: local
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce

