apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nginx-pvc
   namespace: mynginx
spec:
  resources:
    requests: 
       storage: 2Gi
  storageClassName: local
  accessModes:
  - ReadWriteOnce
