# Default values for nginx-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: nginx
  tag: 1.17.3

service:
  nodeport: 30083

